### ISSUE TITLE
Unified Login and Registration Page Design

### ISSUE THREAD

**Issue by anurag629** [anurag629/codercops-site#20]
### **Issue: Login and Registration Page Development**

Develop a cohesive and visually appealing Login and Registration page that mirrors the elegant style seen on the [codercops.tech](https://www.codercops.tech/) website. This feature will enhance the user experience by providing a seamless and consistent design for both functions.

#### **Objective**
The objective of this task is to create a unified Login and Registration page for our website by following these steps:

1. Create a new folder within the `components` directory.
2. Inside the newly created folder, establish a TypeScript (tsx) file named `LoginRegistration.tsx`.
3. Develop a TypeScript (tsx) component that combines both the Login and Registration functionalities within this file.
4. In the `app` directory, create a new subfolder named `loginregistration`.
5. Inside the `loginregistration` folder, generate a `page.tsx` file.
6. Utilize the previously created `LoginRegistration` component within this `page.tsx` file.

#### **Instructions**

1. Begin by creating a dedicated folder in the `components` directory to house the Login and Registration page.

2. Within this folder, generate a TypeScript (tsx) file named `LoginRegistration.tsx`.

3. Develop a unified Login and Registration page using Next.js and TypeScript in the `LoginRegistration.tsx` file. Ensure that it encompasses all the necessary functionalities and adheres to the website's styling and design standards.

4. In the `app` directory, create a new subfolder named `loginregistration`.

5. Inside the `loginregistration` folder, craft a TypeScript (tsx) file named `page.tsx`.

6. Import and employ the `LoginRegistration` component created earlier within this `page.tsx` file.

#### **Testing**

1. Initiate the development server using the appropriate command.

2. Access the local server at the designated URL (e.g., `127.0.0.0:8000/loginregistration/`) in your web browser to view and verify the changes made to the Login and Registration page.

#### **Completion Criteria**
- The Login and Registration page should be fully functional, providing users with the ability to log in or register for an account.
- The page design and style must align with the overall website aesthetic and offer a seamless user experience.

**Comment by AnnieDebbie** [comment]
Hello @anurag629, I would like to work on this issue and #21 along with a product designer friend @baylx
For the registration page, would the following fields suffice: 
- first name
- last name
-  email
-  password
- confirm password

**Comment by anurag629** [comment]
> Hello @anurag629, I would like to work on this issue and #21 along with a product designer friend @Baylx For the registration page, would the following fields suffice:
> 
> * first name
> * last name
> * email
> * password
> * confirm password
>   You can assign both issues to us

sure, go ahead

**Comment by anurag629** [comment]
@AnnieDebbie @Baylx Also add the social Login/Signup with the GitHub button.

**Comment by AnnieDebbie** [comment]
> @AnnieDebbie @Baylx Also add the social Login/Signup with the GitHub button.

Alright

**Comment by AnnieDebbie** [comment]
Hello @anurag629, I hope you are well. I'm sorry for being MIA. I am new to the Next JS framework and have a regular job. 
Updates:
- The newsletter is undergoing a redesign. 
- Development of the login/registration page is about 95% done; just some design changes left for the light mode theme. I'll be raising a Pull Request later today

Thanks for your understanding

**Comment by AnnieDebbie** [comment]
Hello @anurag629 any updates?
